[package]
name = "oaclt_macros"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.73.0"

[lib]
proc-macro = true

[dependencies]
itertools = "0.11.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"
