name: rustup toolchain install from file
description: Install the Rust toolchain from a rust-toolchain file

inputs:
  targets:
    required: false
  components:
    required: false

runs:
  using: composite

  steps:
    - id: read-rust-toolchain
      shell: bash
      run: echo "toolchain=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.read-rust-toolchain.outputs.toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
